import { Topic } from '@/type'

const QUESTION: Topic = {
	'2023/05/25': {
		Girl: '女孩',
		Boy: '男孩',
		Sun: '太陽',
		Moon: '月亮',
		Sky: '天空',
		Sea: '海洋',
		Fire: '火',
		Wind: '風',
		Rain: '雨',
		Snow: '雪',
		Tree: '樹',
		Flower: '花',
		Bird: '鳥',
		Fish: '魚',
		Cat: '貓',
		Dog: '狗',
		Book: '書',
		Pen: '筆',
		Music: '音樂',
		Dance: '舞蹈',
		Smile: '微笑',
		Love: '愛',
		Dream: '夢想',
		Hope: '希望',
		Joy: '喜悅',
		Peace: '和平',
		Friend: '朋友',
		Life: '生活',
		Heart: '心',
		Time: '時間',
		Beauty: '美麗',
		Light: '光',
		Road: '道路',
		Star: '星星',
		Wave: '波浪',
		Mountain: '山',
		Forest: '森林',
		Lake: '湖',
		Bridge: '橋',
		City: '城市',
		Journey: '旅程',
		Adventure: '冒險',
		Wisdom: '智慧',
		Happiness: '幸福',
		Success: '成功',
		Family: '家庭',
		Home: '家',
		Food: '食物',
		Water: '水',
	}
}
export { QUESTION }