import { Topic } from '@/type'

const QUESTION: Topic = {
	'2023/05/23': {Sky: '天空',
		River: '河流',
		Earth: '地球',
		Star: '星星',
		Wind: '风',
		Fire: '火',
		Rain: '雨',
		Snow: '雪',
		Moon: '月亮',
		Sun: '太阳',
		Tree: '树',
		Flower: '花朵',
		Grass: '草',
		Bird: '鸟',
		Fish: '鱼',
		Cat: '猫',
		Dog: '狗',
		Lion: '狮子',
		Tiger: '老虎',
		Bear: '熊',
		Horse: '马',
		Cow: '牛',
		Sheep: '羊',
		Monkey: '猴子',
		Elephant: '大象',
		Giraffe: '长颈鹿',
		Dolphin: '海豚',
		Turtle: '海龟',
		Snake: '蛇',
		Bee: '蜜蜂',
		Butterfly: '蝴蝶',
		Ant: '蚂蚁',
		Spider: '蜘蛛',
		Dragonfly: '蜻蜓',
		Ladybug: '瓢虫',
		Mountain: '山',
		Forest: '森林',
		Desert: '沙漠',
		Island: '岛',
		Beach: '海滩',
		Valley: '山谷',
		Cave: '洞穴',
		Waterfall: '瀑布',
		Lake: '湖泊',
		Ocean: '海洋',
		Sunrise: '日出',
		Sunset: '日落',
		Cloud: '云',
		Thunder: '雷',
		Lightning: '闪电',
	}
}
export { QUESTION }