import { Topic } from '@/type'

const QUESTION: Topic = {
	'2023/05/24': {
		Day: '日',
		Night: '夜晚',
		Sky: '天空',
		Star: '星星',
		Moon: '月亮',
		Sun: '太阳',
		Wind: '风',
		Rain: '雨',
		Snow: '雪',
		Cloud: '云',
		Tree: '树',
		Flower: '花',
		Grass: '草',
		River: '河流',
		Lake: '湖泊',
		Ocean: '海洋',
		Beach: '海滩',
		Mountain: '山',
		Forest: '森林',
		Bird: '鸟',
		Fish: '鱼',
		Cat: '猫',
		Dog: '狗',
		Horse: '马',
		Cow: '牛',
		Sheep: '羊',
		Lion: '狮子',
		Tiger: '老虎',
		Monkey: '猴子',
		Elephant: '大象',
		Giraffe: '长颈鹿',
		Snake: '蛇',
		Bee: '蜜蜂',
		Butterfly: '蝴蝶',
		Ant: '蚂蚁',
		Spider: '蜘蛛',
		Dragonfly: '蜻蜓',
		Ladybug: '瓢虫',
		Fire: '火',
		Ice: '冰',
		Earth: '地球',
		Stone: '石头',
		Sand: '沙',
		Air: '空气',
		Light: '光',
		Dark: '黑暗',
		Sound: '声音',
		Music: '音乐',
		Dance: '舞蹈',
		Art: '艺术',
	}
}
export { QUESTION }