const CONST = {
  JUMP_TO_HOME_SEC: 5000,
	RELOAD_DATA_SEC: 2000,
	QUESTION_TYPE: {
		CHOICE_QUESTION: 'choice',
		BLANK_FILLING_QUESTION: 'blankFilling'
	},
	QUESTION_COUNT: {
		TEN: 10,
		TWENTY: 20,
		THIRTY: 30
	},
	INPUT_MAX_LENGTH: 30,
	CHOICE_OPTIONS_LENGTH: 4
}

export { CONST }
